### PR TITLE
Added french and italian translations

### PR DESCRIPTION
**Pull request by Valem**
Hi

I added the french and italian translations.

Appreciate if you can merge it with the main trunk.

thx
Valem

### CODE REVIEW

**Comment by Valem** [comment]
Hi

Do you have any intensions to push a new NuGet Package version with the translations to NuGet Gallery soon ?

Thanks!
Valem

**Comment by Valem** [comment]
Hi 

Any update on this ?

Appreciate!
Valem

**Comment by TechnoAg** [comment]
Valem,

I'm working on moving our build process to automatically update Nuget. Give me a few days, I won't forget about you!

Thanks,
Alan

**Comment by marinkobabic** [comment]
Hi Alan

Have done this task here 
https://github.com/elliotritchie/NES

Maybe you can reuse it :-)

Thanks
Marinko

**Pull request merged**
