### PR TITLE
Add german resource file

### PR DESCRIPTION
**Pull request by marinkobabic**

### CODE REVIEW

**Comment by marinkobabic** [comment]
- there is just one warning in the NestedValidationResult and the result is valid
- the parentContext Level is error but also valid

because the parentContext Level is error, the result is not valid which makes no sense to me. Both validations are valid so the whole validation result must be valid

**Comment by marinkobabic** [comment]
If an exception occures inside of a custom rule or the list contains an null item, it's very hard to figure out where the exception comes from

**Comment by rbell** [comment]
Marinko,

How would you feel about being added directly to the project as a project
contributor?

Randy

**Comment by marinkobabic** [comment]
Hi Randy

I can do this, but you need to go through the code and merge it. You will have time to do this?

I have already made some pull requests.

Thanks,

Marinko

**Comment by rbell** [comment]
Hey Marinko,

Got your pull request finally merged.  

I had conversation with Alan on Friday.  We want to focus on the following for next release:
- "Else" statement support in fluent DSL.  Right now we support If statements but not "Else".  Else is supported by simply defining multiple rules with if statements - which is not as elegant.
- Support for popular third party IOS frameworks.  When you initialize the Catalog, your really simply initializing our very own simple implementation of an IOC/DI framework.  The reason we did this is that we did not want to bring in any external dependencies to this framework.  However, many don't like having to initialize two IOCs and would like to simply rely on the one they currently use.
- Improved, updates support for MVC, including templates.

Would you have 1) any interest in contributing to any of this, and 2) any time to do so?  Also, you may have some other ideas that might prove helpful!  Bring em!  I can't promise we will adopt all ideas - Lord knows how many of my ideas get shot down by Alan and vice-versa too!  However, I can promise to listen to them and discuss them thoroughly.

If you have this interest, and time, let me know!

Randy

**Comment by marinkobabic** [comment]
Hi Randy

Great news J

Have you also been able to merge this pull request https://github.com/rbell/SpecExpress/commit/80b069d9e5f9da6f9671bf92938bc211d5a3f8bc . We had the problem of NullReferenceException using the Expect statement. Based on the actual error message we never have been able to figure out which specification caused the NullReferenceException. This change should simplify the investigation.

Do you have already an interface which must be implemented for the integration of the third party IOC? I didn’t found your simple implementation of an IOC/DI framework on github, so please send me the link to the github source code class. Here I would be interested to implement the Unity DI Container for you J

Thanks

Marinko

**Comment by marinkobabic** [comment]
Hi guys

Not really working on this project?

Thanks

Marinko

**Comment by marinkobabic** [comment]
Hi Randy

It’s seem like you are no longer working on this framework? If so I would create a brunch and start to use my customized version of this framework.

Thanks

Marinko

**Comment by rbell** [comment]
Hi Marinko,

Allen just checked in a few fixes earlier this week.  I am still trying to
get my laptop reconfigured with PSAKE so that I can run the script to build
the NUGET packages and get them updated.

Allan is also working on and possibly having to rewrite the Catalog
container to better facilitate the integration with other DI/IOC
frameworks.  He has a plan and has a good portion done.

I have made progress on adding an "Else" clause to use in conjunction with
"If".  However, given his rewrite, I am thinking that there could be a
whole lot of collisions and so I am holding off to see the impact on his
rewrite.

I will be visiting Allen in person in a couple weeks and will get a status
then.  I also want to discuss with him adding you to the project as a
resource - giving you access directly to make updates directly to the
repository.  IMO, if we do that, we need to get better organized and
brainstorm up a more complete backlog.

Randy

**Comment by marinkobabic** [comment]
Hi Randy

Good news. I have seen, that you have made a new package. The german resource dll is missed in the package, so the translation does still not work. 

If I do ToString() on ValidationNotification which has no errors, I will get an exception.

In generally why the following scenario is not supported:

Car : Vehicle

VehicleSpecification : Validates<Vehicle>

The VehicleSpecification is not abstract and to get all interfaces and base classes of the type which we are going to validate is not a challenge. You would suggest to Use another specification inside of the VehicleSpecification but this way no generic validation concept can be implemented. If the custom framework has no idea what classes are deriving from vehicle, there is no way to validate them.

If I write a generic framework, which validates all objects for one of object no specification is found, an exception is raised. I think this must be an option in the specexpress framework.

Why not move all to github. Actually if somebody evaluates the framework, they will realize that issues since 2013 are still not solved. So they will not use the framework.

What are your thoughts?

Thanks

Marinko

**Comment by marinkobabic** [comment]
Hi Randy

A friend of mine will do in the next few days a pull request for the french and italian language. 

·         So I hope you will fix the nuget package, to cantain also the resource dlls as well. 

·         It would helpful in the nuget package version would be the same like the dll version.

·         What about the dependency injection, I would like to implement Unity but I can’t see anything related to DI implementation in your actual code? Should I do the implementation and make a pull request?

Thanks

Marinko

**Pull request merged**
